//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAME_Shrink.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAME_Shrink.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adding data to the grid.
        /// </summary>
        internal static string AddingDataToGrid {
            get {
                return ResourceManager.GetString("AddingDataToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bios.
        /// </summary>
        internal static string Bios {
            get {
                return ResourceManager.GetString("Bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By Mame configuration.
        /// </summary>
        internal static string ByMameConfiguration {
            get {
                return ResourceManager.GetString("ByMameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [{0}/{1}] Checking {2} - {3}.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The checks highlighted some warnings.
        /// </summary>
        internal static string CheckingResults {
            get {
                return ResourceManager.GetString("CheckingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Checking romset.
        /// </summary>
        internal static string CheckingRomset {
            get {
                return ResourceManager.GetString("CheckingRomset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clean confirmation.
        /// </summary>
        internal static string CleanConfirmation {
            get {
                return ResourceManager.GetString("CleanConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Could not read file {0}.
        /// </summary>
        internal static string CouldNotReadFile {
            get {
                return ResourceManager.GetString("CouldNotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a disk space {0}.
        /// </summary>
        internal static string DiskSpace {
            get {
                return ResourceManager.GetString("DiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while loading ArcadeItalia.net.
        ///Please retry later.
        /// </summary>
        internal static string ErrorLoadingArcadeItalia {
            get {
                return ResourceManager.GetString("ErrorLoadingArcadeItalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to connect to ArcadeDatabase website, some features will be disabled.
        ///The next time you restart the application, another connection attempt will be made.
        ///
        ///If your PC does not have internet access, change the program options to avoid this message at each startup..
        /// </summary>
        internal static string ErrorLoadingArcadeItaliaVerbose {
            get {
                return ResourceManager.GetString("ErrorLoadingArcadeItaliaVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error loading file.
        /// </summary>
        internal static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error opening url.
        /// </summary>
        internal static string ErrorOpeningUrl {
            get {
                return ResourceManager.GetString("ErrorOpeningUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error selecting file.
        /// </summary>
        internal static string ErrorSelectingFile {
            get {
                return ResourceManager.GetString("ErrorSelectingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error selecting folder.
        /// </summary>
        internal static string ErrorSelectingFolder {
            get {
                return ResourceManager.GetString("ErrorSelectingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Since this operation is not reversible, I ask you for a second confirmation before proceeding to delete {0} game(s).
        ///
        ///Do I proceed?.
        /// </summary>
        internal static string GamesRemoval2ndConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemoval2ndConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm the removal of {0} game(s)?.
        /// </summary>
        internal static string GamesRemovalConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete {0}games?
        ///
        ///NOTE: The files will be moved to the temporary folder {1}.
        /// </summary>
        internal static string GamesRemovalMoveConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalMoveConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete {0} games?
        ///
        ///NOTE: I will try to move the files to the trash if possible.
        /// </summary>
        internal static string GamesRemovalTrashConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalTrashConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid update.
        /// </summary>
        internal static string GridUpdate {
            get {
                return ResourceManager.GetString("GridUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loading ArcadeItalia.net.
        /// </summary>
        internal static string LoadingArcadeItalia {
            get {
                return ResourceManager.GetString("LoadingArcadeItalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mechanical.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing xml file.
        /// </summary>
        internal static string MissingXmlFile {
            get {
                return ResourceManager.GetString("MissingXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No game selected.
        /// </summary>
        internal static string NoGameSelected {
            get {
                return ResourceManager.GetString("NoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No rom selected.
        /// </summary>
        internal static string NoRomSelected {
            get {
                return ResourceManager.GetString("NoRomSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not used anymore by.
        /// </summary>
        internal static string NotUsedAnymoreBy {
            get {
                return ResourceManager.GetString("NotUsedAnymoreBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation completed.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing type not supported.
        /// </summary>
        internal static string ProcessingTypeNotSupported {
            get {
                return ResourceManager.GetString("ProcessingTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading rom folder files {0}.
        /// </summary>
        internal static string ReadingRomFolderFiles {
            get {
                return ResourceManager.GetString("ReadingRomFolderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading roms.
        /// </summary>
        internal static string ReadingRoms {
            get {
                return ResourceManager.GetString("ReadingRoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Required by.
        /// </summary>
        internal static string RequiredBy {
            get {
                return ResourceManager.GetString("RequiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Romset cleaning {0} - {1}.
        /// </summary>
        internal static string RomsetCleaning {
            get {
                return ResourceManager.GetString("RomsetCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Romset validation failed.
        /// </summary>
        internal static string RomsetValidationFailed {
            get {
                return ResourceManager.GetString("RomsetValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screen.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} selected game(s).
        /// </summary>
        internal static string SelectedGames {
            get {
                return ResourceManager.GetString("SelectedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} total game(s).
        /// </summary>
        internal static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Try creating the file manually by typing this command from a terminal window.
        /// </summary>
        internal static string TryGamelistCreationCommandMessage {
            get {
                return ResourceManager.GetString("TryGamelistCreationCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use rom of.
        /// </summary>
        internal static string UseRomOf {
            get {
                return ResourceManager.GetString("UseRomOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There were problems reading the options, default values ​​will be used.
        /// </summary>
        internal static string UserPreferencesLoadingFailure {
            get {
                return ResourceManager.GetString("UserPreferencesLoadingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Website is under maintenance.
        /// </summary>
        internal static string WebSiteUnderMaintenance {
            get {
                return ResourceManager.GetString("WebSiteUnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
