//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAME_Shrink.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAME_Shrink.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adding data to the grid.
        /// </summary>
        internal static string AddingDataToGrid {
            get {
                return ResourceManager.GetString("AddingDataToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bios.
        /// </summary>
        internal static string Bios {
            get {
                return ResourceManager.GetString("Bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By Mame configuration.
        /// </summary>
        internal static string ByMameConfiguration {
            get {
                return ResourceManager.GetString("ByMameConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [{0}/{1}] Checking {2} - {3}.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The checks highlighted some warnings.
        /// </summary>
        internal static string CheckingResults {
            get {
                return ResourceManager.GetString("CheckingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Checking romset.
        /// </summary>
        internal static string CheckingRomset {
            get {
                return ResourceManager.GetString("CheckingRomset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clean confirmation.
        /// </summary>
        internal static string CleanConfirmation {
            get {
                return ResourceManager.GetString("CleanConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Buttons.
        /// </summary>
        internal static string ColumnButtons {
            get {
                return ResourceManager.GetString("ColumnButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        internal static string ColumnCategory {
            get {
                return ResourceManager.GetString("ColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone.
        /// </summary>
        internal static string ColumnClone {
            get {
                return ResourceManager.GetString("ColumnClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File size.
        /// </summary>
        internal static string ColumnFileSize {
            get {
                return ResourceManager.GetString("ColumnFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genre.
        /// </summary>
        internal static string ColumnGenre {
            get {
                return ResourceManager.GetString("ColumnGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manufacturer.
        /// </summary>
        internal static string ColumnManufacturer {
            get {
                return ResourceManager.GetString("ColumnManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Players.
        /// </summary>
        internal static string ColumnPlayers {
            get {
                return ResourceManager.GetString("ColumnPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Release.
        /// </summary>
        internal static string ColumnRelease {
            get {
                return ResourceManager.GetString("ColumnRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Romset.
        /// </summary>
        internal static string ColumnRomset {
            get {
                return ResourceManager.GetString("ColumnRomset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screen.
        /// </summary>
        internal static string ColumnScreen {
            get {
                return ResourceManager.GetString("ColumnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Serie.
        /// </summary>
        internal static string ColumnSerie {
            get {
                return ResourceManager.GetString("ColumnSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        internal static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Title.
        /// </summary>
        internal static string ColumnTitle {
            get {
                return ResourceManager.GetString("ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Year.
        /// </summary>
        internal static string ColumnYear {
            get {
                return ResourceManager.GetString("ColumnYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Could not read file {0}.
        /// </summary>
        internal static string CouldNotReadFile {
            get {
                return ResourceManager.GetString("CouldNotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a disk space {0}.
        /// </summary>
        internal static string DiskSpace {
            get {
                return ResourceManager.GetString("DiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while loading ArcadeItalia.net.
        ///Please retry later.
        /// </summary>
        internal static string ErrorLoadingArcadeItalia {
            get {
                return ResourceManager.GetString("ErrorLoadingArcadeItalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to connect to ArcadeDatabase website, some features will be disabled.
        ///The next time you restart the application, another connection attempt will be made.
        ///
        ///If your PC does not have internet access, change the program options to avoid this message at each startup..
        /// </summary>
        internal static string ErrorLoadingArcadeItaliaVerbose {
            get {
                return ResourceManager.GetString("ErrorLoadingArcadeItaliaVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error loading file.
        /// </summary>
        internal static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error opening url.
        /// </summary>
        internal static string ErrorOpeningUrl {
            get {
                return ResourceManager.GetString("ErrorOpeningUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error selecting file.
        /// </summary>
        internal static string ErrorSelectingFile {
            get {
                return ResourceManager.GetString("ErrorSelectingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error selecting folder.
        /// </summary>
        internal static string ErrorSelectingFolder {
            get {
                return ResourceManager.GetString("ErrorSelectingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Artwork.
        /// </summary>
        internal static string FilterArtwork {
            get {
                return ResourceManager.GetString("FilterArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not required.
        /// </summary>
        internal static string FilterArtworkNotRequired {
            get {
                return ResourceManager.GetString("FilterArtworkNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Required.
        /// </summary>
        internal static string FilterArtworkRequired {
            get {
                return ResourceManager.GetString("FilterArtworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio.
        /// </summary>
        internal static string FilterAudio {
            get {
                return ResourceManager.GetString("FilterAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio mono.
        /// </summary>
        internal static string FilterAudioMono {
            get {
                return ResourceManager.GetString("FilterAudioMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio multichannel.
        /// </summary>
        internal static string FilterAudioMultichannel {
            get {
                return ResourceManager.GetString("FilterAudioMultichannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio not supported.
        /// </summary>
        internal static string FilterAudioNotSupported {
            get {
                return ResourceManager.GetString("FilterAudioNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio stereo.
        /// </summary>
        internal static string FilterAudioStereo {
            get {
                return ResourceManager.GetString("FilterAudioStereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bios.
        /// </summary>
        internal static string FilterBios {
            get {
                return ResourceManager.GetString("FilterBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By category.
        /// </summary>
        internal static string FilterByCategory {
            get {
                return ResourceManager.GetString("FilterByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By genre.
        /// </summary>
        internal static string FilterByGenre {
            get {
                return ResourceManager.GetString("FilterByGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By release number.
        /// </summary>
        internal static string FilterByReleaseNumber {
            get {
                return ResourceManager.GetString("FilterByReleaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By serie.
        /// </summary>
        internal static string FilterBySerie {
            get {
                return ResourceManager.GetString("FilterBySerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Categories.
        /// </summary>
        internal static string FilterCategories {
            get {
                return ResourceManager.GetString("FilterCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone machine.
        /// </summary>
        internal static string FilterCloneMachine {
            get {
                return ResourceManager.GetString("FilterCloneMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Color.
        /// </summary>
        internal static string FilterColor {
            get {
                return ResourceManager.GetString("FilterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emulated.
        /// </summary>
        internal static string FilterColorEmulated {
            get {
                return ResourceManager.GetString("FilterColorEmulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterColorImperfect {
            get {
                return ResourceManager.GetString("FilterColorImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unemulated.
        /// </summary>
        internal static string FilterColorUnemulated {
            get {
                return ResourceManager.GetString("FilterColorUnemulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Complete.
        /// </summary>
        internal static string FilterComplete {
            get {
                return ResourceManager.GetString("FilterComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completion.
        /// </summary>
        internal static string FilterCompletion {
            get {
                return ResourceManager.GetString("FilterCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string FilterDevice {
            get {
                return ResourceManager.GetString("FilterDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disks.
        /// </summary>
        internal static string FilterDisks {
            get {
                return ResourceManager.GetString("FilterDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use CHD bad dump.
        /// </summary>
        internal static string FilterDiskStatusBadDump {
            get {
                return ResourceManager.GetString("FilterDiskStatusBadDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use CHD good.
        /// </summary>
        internal static string FilterDiskStatusGood {
            get {
                return ResourceManager.GetString("FilterDiskStatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use CHD no dump.
        /// </summary>
        internal static string FilterDiskStatusNoDump {
            get {
                return ResourceManager.GetString("FilterDiskStatusNoDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LCD.
        /// </summary>
        internal static string FilterDisplayLCD {
            get {
                return ResourceManager.GetString("FilterDisplayLCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Raster.
        /// </summary>
        internal static string FilterDisplayRaster {
            get {
                return ResourceManager.GetString("FilterDisplayRaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SVG.
        /// </summary>
        internal static string FilterDisplaySVG {
            get {
                return ResourceManager.GetString("FilterDisplaySVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Display type.
        /// </summary>
        internal static string FilterDisplayType {
            get {
                return ResourceManager.GetString("FilterDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string FilterDisplayUnknown {
            get {
                return ResourceManager.GetString("FilterDisplayUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vector.
        /// </summary>
        internal static string FilterDisplayVector {
            get {
                return ResourceManager.GetString("FilterDisplayVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do not requires CHD.
        /// </summary>
        internal static string FilterDoNotRequiresCHD {
            get {
                return ResourceManager.GetString("FilterDoNotRequiresCHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do not use sample.
        /// </summary>
        internal static string FilterDoNotUseSample {
            get {
                return ResourceManager.GetString("FilterDoNotUseSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Driver.
        /// </summary>
        internal static string FilterDriver {
            get {
                return ResourceManager.GetString("FilterDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cocktail.
        /// </summary>
        internal static string FilterDriverCocktail {
            get {
                return ResourceManager.GetString("FilterDriverCocktail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good.
        /// </summary>
        internal static string FilterDriverCocktailGood {
            get {
                return ResourceManager.GetString("FilterDriverCocktailGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterDriverCocktailImperfect {
            get {
                return ResourceManager.GetString("FilterDriverCocktailImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preliminary.
        /// </summary>
        internal static string FilterDriverCocktailPreliminary {
            get {
                return ResourceManager.GetString("FilterDriverCocktailPreliminary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string FilterDriverCocktailUnknown {
            get {
                return ResourceManager.GetString("FilterDriverCocktailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        internal static string FilterDriverStatus {
            get {
                return ResourceManager.GetString("FilterDriverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterDriverStatusImperfect {
            get {
                return ResourceManager.GetString("FilterDriverStatusImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not working.
        /// </summary>
        internal static string FilterDriverStatusNotWorking {
            get {
                return ResourceManager.GetString("FilterDriverStatusNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string FilterDriverStatusUnknown {
            get {
                return ResourceManager.GetString("FilterDriverStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working.
        /// </summary>
        internal static string FilterDriverStatusWorking {
            get {
                return ResourceManager.GetString("FilterDriverStatusWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emulation.
        /// </summary>
        internal static string FilterEmulation {
            get {
                return ResourceManager.GetString("FilterEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good.
        /// </summary>
        internal static string FilterEmulationGood {
            get {
                return ResourceManager.GetString("FilterEmulationGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterEmulationImperfect {
            get {
                return ResourceManager.GetString("FilterEmulationImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preliminary.
        /// </summary>
        internal static string FilterEmulationPreliminary {
            get {
                return ResourceManager.GetString("FilterEmulationPreliminary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string FilterEmulationUnknown {
            get {
                return ResourceManager.GetString("FilterEmulationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Graphic.
        /// </summary>
        internal static string FilterGraphic {
            get {
                return ResourceManager.GetString("FilterGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emulated.
        /// </summary>
        internal static string FilterGraphicEmulated {
            get {
                return ResourceManager.GetString("FilterGraphicEmulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterGraphicImperfect {
            get {
                return ResourceManager.GetString("FilterGraphicImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unemulated.
        /// </summary>
        internal static string FilterGraphicUnemulated {
            get {
                return ResourceManager.GetString("FilterGraphicUnemulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hardware.
        /// </summary>
        internal static string FilterHardware {
            get {
                return ResourceManager.GetString("FilterHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incomplete.
        /// </summary>
        internal static string FilterInomplete {
            get {
                return ResourceManager.GetString("FilterInomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a License.
        /// </summary>
        internal static string FilterLicense {
            get {
                return ResourceManager.GetString("FilterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Official.
        /// </summary>
        internal static string FilterLicenseOfficial {
            get {
                return ResourceManager.GetString("FilterLicenseOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unofficial.
        /// </summary>
        internal static string FilterLicenseUnofficial {
            get {
                return ResourceManager.GetString("FilterLicenseUnofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machine.
        /// </summary>
        internal static string FilterMachine {
            get {
                return ResourceManager.GetString("FilterMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mamecab.
        /// </summary>
        internal static string FilterMameCab {
            get {
                return ResourceManager.GetString("FilterMameCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mechanical.
        /// </summary>
        internal static string FilterMechanical {
            get {
                return ResourceManager.GetString("FilterMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No categories.
        /// </summary>
        internal static string FilterNoCategories {
            get {
                return ResourceManager.GetString("FilterNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No genre.
        /// </summary>
        internal static string FilterNoGenre {
            get {
                return ResourceManager.GetString("FilterNoGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No series.
        /// </summary>
        internal static string FilterNoSeries {
            get {
                return ResourceManager.GetString("FilterNoSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parent machine.
        /// </summary>
        internal static string FilterParentMachine {
            get {
                return ResourceManager.GetString("FilterParentMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protection.
        /// </summary>
        internal static string FilterProtection {
            get {
                return ResourceManager.GetString("FilterProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emulated.
        /// </summary>
        internal static string FilterProtectionEmulated {
            get {
                return ResourceManager.GetString("FilterProtectionEmulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imperfect.
        /// </summary>
        internal static string FilterProtectionImperfect {
            get {
                return ResourceManager.GetString("FilterProtectionImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unemulated.
        /// </summary>
        internal static string FilterProtectionUnemulated {
            get {
                return ResourceManager.GetString("FilterProtectionUnemulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Release.
        /// </summary>
        internal static string FilterRelease {
            get {
                return ResourceManager.GetString("FilterRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Requires CHD.
        /// </summary>
        internal static string FilterRequiresCHD {
            get {
                return ResourceManager.GetString("FilterRequiresCHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sample.
        /// </summary>
        internal static string FilterSample {
            get {
                return ResourceManager.GetString("FilterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save state.
        /// </summary>
        internal static string FilterSaveState {
            get {
                return ResourceManager.GetString("FilterSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Supported.
        /// </summary>
        internal static string FilterSaveStateSupported {
            get {
                return ResourceManager.GetString("FilterSaveStateSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string FilterSaveStateUnknown {
            get {
                return ResourceManager.GetString("FilterSaveStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unsupported.
        /// </summary>
        internal static string FilterSaveStateUnupported {
            get {
                return ResourceManager.GetString("FilterSaveStateUnupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Four.
        /// </summary>
        internal static string FilterScreenFour {
            get {
                return ResourceManager.GetString("FilterScreenFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a For or more.
        /// </summary>
        internal static string FilterScreenFourOrMore {
            get {
                return ResourceManager.GetString("FilterScreenFourOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Horizontal.
        /// </summary>
        internal static string FilterScreenHorizontal {
            get {
                return ResourceManager.GetString("FilterScreenHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screenless.
        /// </summary>
        internal static string FilterScreenless {
            get {
                return ResourceManager.GetString("FilterScreenless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a More than four.
        /// </summary>
        internal static string FilterScreenMoreThanFour {
            get {
                return ResourceManager.GetString("FilterScreenMoreThanFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No rotation.
        /// </summary>
        internal static string FilterScreenNoRotation {
            get {
                return ResourceManager.GetString("FilterScreenNoRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One.
        /// </summary>
        internal static string FilterScreenOne {
            get {
                return ResourceManager.GetString("FilterScreenOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One or more.
        /// </summary>
        internal static string FilterScreenOneOrMore {
            get {
                return ResourceManager.GetString("FilterScreenOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Orientation.
        /// </summary>
        internal static string FilterScreenOrientation {
            get {
                return ResourceManager.GetString("FilterScreenOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rotated 180 degrees.
        /// </summary>
        internal static string FilterScreenRotated180 {
            get {
                return ResourceManager.GetString("FilterScreenRotated180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rotated 270 degrees.
        /// </summary>
        internal static string FilterScreenRotated270 {
            get {
                return ResourceManager.GetString("FilterScreenRotated270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rotated 90 degrees.
        /// </summary>
        internal static string FilterScreenRotated90 {
            get {
                return ResourceManager.GetString("FilterScreenRotated90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number of screens.
        /// </summary>
        internal static string FilterScreensNumber {
            get {
                return ResourceManager.GetString("FilterScreensNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Three.
        /// </summary>
        internal static string FilterScreenThree {
            get {
                return ResourceManager.GetString("FilterScreenThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Three or more.
        /// </summary>
        internal static string FilterScreenThreeOrMore {
            get {
                return ResourceManager.GetString("FilterScreenThreeOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Two.
        /// </summary>
        internal static string FilterScreenTwo {
            get {
                return ResourceManager.GetString("FilterScreenTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Two or more.
        /// </summary>
        internal static string FilterScreenTwoOrMore {
            get {
                return ResourceManager.GetString("FilterScreenTwoOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical.
        /// </summary>
        internal static string FilterScreenVertical {
            get {
                return ResourceManager.GetString("FilterScreenVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound emulated.
        /// </summary>
        internal static string FilterSoundEmulated {
            get {
                return ResourceManager.GetString("FilterSoundEmulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string FilterSoundHardwareNo {
            get {
                return ResourceManager.GetString("FilterSoundHardwareNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string FilterSoundHardwareYes {
            get {
                return ResourceManager.GetString("FilterSoundHardwareYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound imperfect.
        /// </summary>
        internal static string FilterSoundImperfect {
            get {
                return ResourceManager.GetString("FilterSoundImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound unemulated.
        /// </summary>
        internal static string FilterSoundUnemulated {
            get {
                return ResourceManager.GetString("FilterSoundUnemulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use sample.
        /// </summary>
        internal static string FilterUseSample {
            get {
                return ResourceManager.GetString("FilterUseSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Video.
        /// </summary>
        internal static string FilterVideo {
            get {
                return ResourceManager.GetString("FilterVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Since this operation is not reversible, I ask you for a second confirmation before proceeding to delete {0} game(s).
        ///
        ///Do I proceed?.
        /// </summary>
        internal static string GamesRemoval2ndConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemoval2ndConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm the removal of {0} game(s)?.
        /// </summary>
        internal static string GamesRemovalConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete {0}games?
        ///
        ///NOTE: The files will be moved to the temporary folder {1}.
        /// </summary>
        internal static string GamesRemovalMoveConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalMoveConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete {0} games?
        ///
        ///NOTE: I will try to move the files to the trash if possible.
        /// </summary>
        internal static string GamesRemovalTrashConfirmationMessage {
            get {
                return ResourceManager.GetString("GamesRemovalTrashConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genres.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid update.
        /// </summary>
        internal static string GridUpdate {
            get {
                return ResourceManager.GetString("GridUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loading ArcadeItalia.net.
        /// </summary>
        internal static string LoadingArcadeItalia {
            get {
                return ResourceManager.GetString("LoadingArcadeItalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mechanical.
        /// </summary>
        internal static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Missing xml file.
        /// </summary>
        internal static string MissingXmlFile {
            get {
                return ResourceManager.GetString("MissingXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No game selected.
        /// </summary>
        internal static string NoGameSelected {
            get {
                return ResourceManager.GetString("NoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No item selected.
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No rom selected.
        /// </summary>
        internal static string NoRomSelected {
            get {
                return ResourceManager.GetString("NoRomSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not used anymore by.
        /// </summary>
        internal static string NotUsedAnymoreBy {
            get {
                return ResourceManager.GetString("NotUsedAnymoreBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation completed.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing type not supported.
        /// </summary>
        internal static string ProcessingTypeNotSupported {
            get {
                return ResourceManager.GetString("ProcessingTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading rom folder files {0}.
        /// </summary>
        internal static string ReadingRomFolderFiles {
            get {
                return ResourceManager.GetString("ReadingRomFolderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reading roms.
        /// </summary>
        internal static string ReadingRoms {
            get {
                return ResourceManager.GetString("ReadingRoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Required by.
        /// </summary>
        internal static string RequiredBy {
            get {
                return ResourceManager.GetString("RequiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Romset cleaning {0} - {1}.
        /// </summary>
        internal static string RomsetCleaning {
            get {
                return ResourceManager.GetString("RomsetCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Romset validation failed.
        /// </summary>
        internal static string RomsetValidationFailed {
            get {
                return ResourceManager.GetString("RomsetValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screen.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} selected game(s).
        /// </summary>
        internal static string SelectedGames {
            get {
                return ResourceManager.GetString("SelectedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Series.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} total game(s).
        /// </summary>
        internal static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Try creating the file manually by typing this command from a terminal window.
        /// </summary>
        internal static string TryGamelistCreationCommandMessage {
            get {
                return ResourceManager.GetString("TryGamelistCreationCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update selection.
        /// </summary>
        internal static string UpdateSelection {
            get {
                return ResourceManager.GetString("UpdateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use rom of.
        /// </summary>
        internal static string UseRomOf {
            get {
                return ResourceManager.GetString("UseRomOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There were problems reading the options, default values ​​will be used.
        /// </summary>
        internal static string UserPreferencesLoadingFailure {
            get {
                return ResourceManager.GetString("UserPreferencesLoadingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Website is under maintenance.
        /// </summary>
        internal static string WebSiteUnderMaintenance {
            get {
                return ResourceManager.GetString("WebSiteUnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
