name: Build and Release .NET Framework 4.8

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write
  packages: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Current project workspace
        shell: cmd
        run: |
          echo Current project workspace:
          echo %GITHUB_WORKSPACE%

      - name: Current folder
        shell: cmd
        run: |
          echo Current folder:
          echo %CD%

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "MAME Shrink.sln"

      - name: Clean and Create Release Directory
        shell: pwsh
        run: |
          $releaseBase = "$env:GITHUB_WORKSPACE\release"
          $releaseX64 = Join-Path $releaseBase "x64"
          $releaseX86 = Join-Path $releaseBase "x86"
          if (Test-Path $releaseBase) {
            Remove-Item $releaseBase -Recurse -Force
          }
          New-Item -ItemType Directory -Path $releaseX64 | Out-Null
          New-Item -ItemType Directory -Path $releaseX86 | Out-Null

      - name: Build Solution x64
        run: msbuild "MAME Shrink.sln" /p:Configuration=Release /p:Platform="x64"

      - name: Copy Output Files x64
        shell: pwsh
        run: |
          $sourceDir = Join-Path $env:GITHUB_WORKSPACE "src\bin\x64\Release"
          $destDir = Join-Path $env:GITHUB_WORKSPACE "release\x64"
          $fileListPath = "$env:GITHUB_WORKSPACE\build-filelist.txt"
          Get-Content $fileListPath | ForEach-Object {
              $sourcePath = Join-Path $sourceDir $_
              $destPath = Join-Path $destDir $_
              if (Test-Path $sourcePath) {
                  $destSubDir = Split-Path $destPath -Parent
                  if (-not (Test-Path $destSubDir)) {
                      New-Item -ItemType Directory -Path $destSubDir -Force | Out-Null
                  }
                  Copy-Item -Path $sourcePath -Destination $destPath -Force
              } else {
                  Write-Error "❌ File missing: $sourcePath"
              }
          }


      - name: Compress Release Files x64
        run: Compress-Archive -Path release\x64\* -DestinationPath release_x64.zip

      - name: Build Solution x86
        run: msbuild "MAME Shrink.sln" /p:Configuration=Release /p:Platform="x86"

      - name: Copy Output Files x86
        shell: pwsh
        run: |
          $sourceDir = Join-Path $env:GITHUB_WORKSPACE "src\bin\Release"
          $destDir = Join-Path $env:GITHUB_WORKSPACE "release\x86"
          $fileListPath = "$env:GITHUB_WORKSPACE\build-filelist.txt"
          Get-Content $fileListPath | ForEach-Object {
              $sourcePath = Join-Path $sourceDir $_
              $destPath = Join-Path $destDir $_
              if (Test-Path $sourcePath) {
                  $destSubDir = Split-Path $destPath -Parent
                  if (-not (Test-Path $destSubDir)) {
                      New-Item -ItemType Directory -Path $destSubDir -Force | Out-Null
                  }
                  Copy-Item -Path $sourcePath -Destination $destPath -Force
              } else {
                  Write-Error "❌ File missing: $sourcePath"
              }
          }

      - name: Compress Release Files x86
        run: Compress-Archive -Path release\x86\* -DestinationPath release_x86.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Questa è la release automatica per il tag ${{ github.ref_name }}."
          draft: false
          prerelease: false
          files: release_x64.zip, release_x86.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
